modLoader="javafml"
loaderVersion="[30,)"

[[mods]]
modId="morevanillaarmor"
version="${file.jarVersion}"
displayName="MoreVanillaArmor"
updateJSONURL="https://raw.githubusercontent.com/MelanX/MoreVanillaArmor/1.15.x/update/Update.json"
authors="MelanX"
description='''
A mod which adds more armor in the vanilla way.
'''
[[dependencies.MoreVanillaArmor]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.MoreVanillaArmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
