modLoader="javafml"
loaderVersion="[25,)"

[[mods]]
modId="morevanillaarmor"
version="${file.jarVersion}"
displayName="MoreVanillaArmor"
updateJSONURL="https://raw.githubusercontent.com/MelanX/MoreVanillaArmor/1.13.2/update/Update.json"
authors="MelanX"
description='''
A mod which adds more armor in the vanilla way.
'''
[[dependencies.MoreVanillaTools]]
    modId="forge"
    mandatory=true
    versionRange="[25.0.219,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.MoreVanillaTools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"
