modLoader = "javafml"
loaderVersion = "[45,)"
license = "Apache 2.0"

[[mods]]
modId="morevanillaarmor"
version="${file.jarVersion}"
displayName="MoreVanillaArmor"
updateJSONURL="https://assets.melanx.de/updates/morevanillaarmor.json"
authors="MelanX"
description='''
A mod which adds more armor in the vanilla way.
'''

[[dependencies.morevanillaarmor]]
    modId = "forge"
    mandatory = true
    versionRange = "[45.0.66,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.morevanillaarmor]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.4, 1.20)"
    ordering = "NONE"
    side = "BOTH"
