modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT License"

[[mods]]
modId="morevanillaarmor"
version="${file.jarVersion}"
displayName="MoreVanillaArmor"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/morevanillaarmor.json"
authors="MelanX"
description='''
A mod which adds more armor in the vanilla way.
'''

[[dependencies.morevanillaarmor]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.morevanillaarmor]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17.1,)"
    ordering = "NONE"
    side = "BOTH"
